### ISSUE TITLE
Finalize Scraped Attributes

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/SDHACKS-2016#1]
List all desired attributes that will be scraped from restaurant menus. This will help us finalize what information shall be included in the database.

**Comment by mbotsko7** [comment]
The desired attributes are currently going to be as follows:
Name of Restraunt
average cost of the dishes at restraunt (includes everything on menu)
url to restaurant main page (**NOT THE MENU**)
while(there is an item):
   item name
   price

**Comment by jaylenw** [comment]
cool!

**Comment by jaylenw** [comment]
completed for the extent of SD Hacks
